### ISSUE TITLE
movements created by distance matrix code counts multiple GG East/West "movements"

### ISSUE THREAD

**Issue by Myfanwy** [goertler/acoustic-telemetry-synthesis#1]
For example, see FishID ARF2017-005; the code that filters down to the first movement at each receiver counts multiple first "arrivals" at GGE/W; should we group these receivers?  It really adds up the distance "traveled" by this fish, by 826 meters/movement at the GG recs.

**Comment by Myfanwy** [comment]
This is still causing issues, particularly with fish that are only detected at release and then at Chipps.  Suggest choosing a receiver in the middle of the array to represent all arrivals/departures at Chipps, and then grouping all Chipps detections by this. 

Would need to apply this grouping to all cleaning scripts and re-make results.  @goertler , could you take a look at the receiver map and choose a representative receiver from the Chipps array?  We can then assign all other Chipps receivers to that GEN name, and the movements across the Chipps array will be standardized to that distance from the distance matrix.

**Comment by goertler** [comment]
Is this only needed for YBUS? The JSATS estuary detection is a little more complicated because they don't have a Chipps array in all years. Alos, we already use "GEN" locations for JSATS, so maybe that takes care of this issue for that dataset?

**Comment by goertler** [comment]
Otherwise, can we call all the MAL sites in YBUS, GEN = MAL and then we don't need to change the code for the other datasets?

**Comment by goertler** [comment]
@Myfanwy I think I have added the remaining GEN locations to YBUS. One thing I noticed is that we had already renamed these on a previous iteration to match the distance matrix to the detections("YB_BCE", "YB_BCE2","YB_BCW","YB_BCW2", lines 54-57), but now that we have GEN locations, do we want to give them a general name? They are near "CCH.1" & "CCH.2"...
